version: '3.8'

services:
  php-apache:
    container_name: php-apache
    build:
      context: ./docker/php8
    ports:
      - '8082:80'
    volumes:
      - ./:/var/www/html
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf